require("ta.remap")
require("ta.telescope")
require("ta.treesitter")
require("ta.lsp")
require("ta.options")
require("ta.colorscheme")
require("ta.nvim-tree")
require("ta.autocmd")
require("ta.nvim-comment")
require("ta.lualine")
require("ta.packer")
print("chilnn breh")
