vim.opt.relativenumber = true -- display line numbers relative to current line
vim.opt.number = true -- display the current line number instead of 0
vim.opt.colorcolumn = "90" -- shows bar at the X line length
vim.opt.scrolloff = 8 -- when to start scrolling
vim.opt.sidescrolloff = 8 -- when to scroll horizontally
vim.opt.tabstop = 2 -- insert X for tabs
vim.opt.shiftwidth = 2 -- insert X spaces for indentation
vim.opt.hidden = true
vim.opt.hlsearch = true -- highlight all matches on previous search pattern
vim.opt.ignorecase = true -- ignore case in search pattern
vim.opt.smartcase = true -- smart case
vim.opt.smartindent = true -- make indenting smarter again
vim.opt.splitbelow = true -- force all horizontal splits to go below current window
vim.opt.splitright = true -- force all vertical splits to go to the right of current window
vim.opt.expandtab = true -- convert tabs to spaces
vim.opt.showmode = true
vim.opt.undodir = vim.fn.stdpath "cache" .. "/undo"
vim.opt.undofile = true -- enable persistent undo
vim.opt.updatetime = 300 -- faster completion
vim.opt.writebackup = false -- if a file is being edited by another program (or was written to file while editing with another program) it is not allowed to be edited
vim.opt.signcolumn = "yes"
vim.opt.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
vim.opt.swapfile = false -- creates a swapfile
vim.opt.termguicolors = true -- set term gui colors (most terminals support this)
vim.opt.timeoutlen = 500 -- time to wait for a mapped sequence to complete (in milliseconds)
vim.opt.wrap = false -- display lines as one long line
vim.opt.spell = false
-- vim.opt.laststatus = 3 -- turn on global status line
